version: '3.9'

services:

  authentication-module:
    image: "authentication-module"
    container_name: "authentication-module"
    build: 
      context: "."
      target: "development"
      dockerfile: "dockerfile"
    ports:
    - "80:80"
    volumes:
    - "../www:/var/www/html"
    - "../Library:/var/www/Library"
    - "./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    - "./apache/apache2.conf:/etc/apache2/apache2.conf"
    restart: always
    networks:
      authentication-module:
        ipv4_address: 172.100.0.2

  user-db:
    image: mariadb:10.5.16
    container_name: "user-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "users"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - ../Database/User/Data:/var/lib/mysql
      - ../Database/User/Data/mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    networks:
      authentication-module:
        ipv4_address: 172.100.0.3
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - user-db:db
    ports:
      - '8080:80'
    environment:
      MYSQL_USER: "authentication"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      authentication-module:
        ipv4_address: 172.100.0.4
  
networks:
  authentication-module:
    driver: bridge
    ipam:
     config:
       - subnet: 172.100.0.0/16
         gateway: 172.100.0.1