version: '3.9'

services:
  user-module:
    image: "user-module"
    container_name: "user-module"
    build: 
      context: "."
      target: "development"
      dockerfile: "dockerfile"
    environment:
        BFF: "http://172.18.0.3/"
    ports:
    - "80:80"
    volumes:
    - "../Web:/var/www/html"
    - "./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    - "./apache/apache2.conf:/etc/apache2/apache2.conf"
    restart: always
    networks:
      user-module:
        ipv4_address: 172.18.0.2

  user-db:
    image: "user-db"
    container_name: "user-db"
    build:
        context: "."
        target: "mariadb"
        dockerfile: "dockerfile"
    environment:
        MYSQL_ROOT_PASSWORD: "abcd1234"
        MYSQL_DATABASE: "user"
        MYSQL_USER: "custom"
        MYSQL_PASSWORD: "abcd1234"
    ports:
        - "3306:3036"
    volumes:
        - "../Database/Script:/docker-entrypoint-initdb.d"
    restart: always
    networks:
      user-module:
        ipv4_address: 172.18.0.3
        

networks:
  user-module:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1