version: '3.9'

services:

  authentication-module:
    image: "authentication-module"
    container_name: "authentication-module"
    build: 
      context: "."
      target: "development"
      dockerfile: "dockerfile"
    ports:
    - "80:80"
    volumes:
    - "../www:/var/www/html"
    - "../Library:/var/www/Library"
    - "./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    - "./apache/apache2.conf:/etc/apache2/apache2.conf"
    environment:
      DOMAIN: "http://localhost/"
      API: "http://localhost/api/"
      LIBRARY: "/var/www/Library/"
      DB: "/var/www/Library/Commons/Db/Db.php"
      SHOW_ERROR: 1
      SHOW_SQL: 1
      JWT_KEY: '1J7Z9eEVWzUUo0X3^%1LP12x6j%FI4Y5u4f9X@0X3%1LP12x6Fz@oReLQDcb'
    restart: always
    networks:
      authentication-module:
        ipv4_address: 172.100.0.2

  user-db:
    image: mariadb:10.5.16
    container_name: "user-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "users"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - ../Database/User/Data:/var/lib/mysql
      - ../Database/User/Data/mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    networks:
      authentication-module:
        ipv4_address: 172.100.0.3
  
  user-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "user-phpmyadmin"
    links: 
      - user-db:db
    ports:
      - '8080:80'
    environment:
      MYSQL_USER: "authentication"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      authentication-module:
        ipv4_address: 172.100.0.4

  authentication-db:
    image: mariadb:10.5.16
    container_name: "authentication-db"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "authentications"
      MYSQL_USER: "authentication"
      MYSQL_PASSWORD: "root"
    ports:
      - 3307:3306
    volumes:
      - ../Database/Authentication/Data:/var/lib/mysql
      - ../Database/Authentication/Data/mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    networks:
      authentication-module:
        ipv4_address: 172.100.0.5
  
  authentication-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "authentication-phpmyadmin"
    links: 
      - authentication-db:db
    ports:
      - '8081:80'
    environment:
      MYSQL_USER: "authentication"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_PORT: 3307
    networks:
      authentication-module:
        ipv4_address: 172.100.0.6

networks:
  authentication-module:
    driver: bridge
    ipam:
     config:
       - subnet: 172.100.0.0/16
         gateway: 172.100.0.1